### ISSUE TITLE
Rejection of copyleft in code

### ISSUE THREAD

**Issue by davidread** [theodi/ODI#12]
@agentGav can you explain why ODI doesn't allow copy-left in code licences?
https://github.com/theodi/ODI/blob/master/charter/standards.md

Is ODI really saying there are no circumstances when GPL is appropriate for code that it writes or commissions? That stance would seem un-open and dogmatic. Is Linux so bad?!

e.g. https://github.com/opendata/CKAN-Multisite/issues/6#issuecomment-66403452

I understand that you might want to generally write code as MIT, but do you really feel that there really NO circumstances when GPL might be appropriate? When you're trying to build a standard piece of open infrastructure in the midst of fierce commercial competition that is not-open (e.g. CKAN) then copy-left is a most valuable tool in keeping it thriving and protected from 'embrace and extend' tactics.

**Comment by agentGav** [comment]
Thanks for your comment. I've answered here https://github.com/theodi/ODI/issues/11
